services:
  - type: web
    name: deedpro-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port 8000"
    healthCheckPath: "/health"
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    scaling:
      minInstances: 1
      maxInstances: 3
    domains:
      - deedpro-api.onrender.com 